### ISSUE TITLE
Is it possible if we modify update location user in a minutes not based on latest location user?

### ISSUE THREAD

**Issue by wahyubudii** [royer/simple_bg_location#4]

**Comment by royer** [comment]
What does “update location user” mean ? I could not understand. Could you explain more detail?

**Comment by wahyubudii** [comment]
basically location would be update after user move right? so is it possible if i change the methode that i would to get current location user after 5 minutes at a time for example cause i wanna combine with send an api

**Comment by royer** [comment]
Location information is usually obtained through subscription. When submitting a subscription request, you can set the interval for sending messages. This way, your application will receive current location information at the intervals you specified, even if the user hasn't moved.  You don't need to call the getCurrentLocation API every 5 minutes to get the current location.

**Comment by wahyubudii** [comment]
i tried to implement your suggestion into my program code by giving an interval of 5 minutes, but unfortunately getting the user's current location is still based on user movement rather than the time interval itself. Actually, this time interval runs well but does not execute the update of the user's current location. Can you provide an example of the program code of what you mean?

**Comment by royer** [comment]
iOS or Android?

**Comment by royer** [comment]
> i tried to implement your suggestion into my program code by giving an interval of 5 minutes, but unfortunately getting the user's current location is still based on user movement rather than the time interval itself. Actually, this time interval runs well but does not execute the update of the user's current location. Can you provide an example of the program code of what you mean?

OK. I check my source, I setMinUpdateDistanceMeters default 5 meter. so on android if move distance less 5 meter will not update.  because it will save power. you can set requestSettings.distanceFilter = 0 when call requestPositionUpdate to receive update if user not move.
